name: resto
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - VITE_API_URL=http://localhost:8082
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8082:3000"
    environment:
      - MONGODB_URI=mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-secretpassword}@mongodb:27017/resto?authSource=admin
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017    
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-resto}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-secretpassword}
    command: ["mongod", "--auth"]

volumes:
  mongodb_data: