name: resto
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8082:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/resto
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-secretpassword}
    command: ["mongod", "--auth"]

volumes:
  mongodb_data: